### ISSUE TITLE
Cambiar la descripción del repo

### ISSUE THREAD

**Issue by arielmerin** [RRSaul/proyect1#1]
La descripcion breve, es aquella que aparece justo debajo del nombre

**Comment by arielmerin** [comment]
I mean estaría chido que lo cambiaras, se ve bonito y además que le pusieras los horarios como van (recuerda que yo lo deje en domingo y la hora mal)


en fin, esto de ponerte un issue sólo es para introducirte a esta modalidad en github

**Comment by RRSaul** [comment]
Va
